---
# tasks file for apache
- name: Install httpd
  package:
        name: "{{package_name}}"
        state: present
  tags:
        - install

- name: Start the httpd Daemon
  systemd:
        name: "{{package_name}}"
        state: started
        enabled: yes
  tags:
        - daemon

- name: Copy index file to target
  copy:
        src: index.html  # Specify the correct path to your index.html file
        dest: /var/www/html/index.html
  tags:
        - file_copy
  notify:
        - Restart Apache
       