---
- hosts: db
  become: true
  gather_facts: false
  tasks:
    - name: Update the system
      yum:
        name: '*'
        state: latest
      tags:
        - update

    - name: Install httpd
      package:
        name: httpd
        state: present
      tags:
        - install

    - name: Start the httpd Daemon
      systemd:
        name: httpd
        state: started
        enabled: true
      tags:
        - daemon
    - name: Change directory to the html directory
      shell:
        cmd: cd /var/www/html

    - name: Copy index file to target
      copy:
        src: index.html  # Specify the correct path to your index.html file
        dest: /var/www/html/index.html
      tags:
        - file_copy
      notify:
        - Restart Apache

  handlers:
    - name: Restart Apache
      systemd:
        name: httpd
        state: restarted




#yum update -y
#yum install httpd -y
#systemctl start httpd
#systemctl enable httpd
# cd /var/www/html
# touch index.html
# vi 
